import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import NavbarComponent from "@/app/(client-panel)/Navbar";
import Hero from "./(client-panel)/Hero";
import Footer from "./(client-panel)/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Hero />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
